name: Issue Comment Test
on:
  issue_comment:
    types:
      - created
      - deleted
      - edited
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "WORKS!""
      - name: GH context
        env:
          GH: ${{ toJson(github)}}
        run: |
          echo -e "Github context:\n$GH"
