name: Deploy
run-name: Deploy conditions test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - edited

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.state == 'open' && (
        contains(github.event.pull_request.labels.*.name, 'deploy') ||
        endsWith(github.event.pull_request.title, '[deploy]')
      ) && (
        contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action) ||
        github.event.action == 'labeled' && github.event.label.name == 'deploy' ||
        github.event.action == 'edited' && endsWith(github.event.pull_request.title, '[deploy]')
      )
    steps:
      - run: echo "Start"
      - name: GH context
        env:
          GH: ${{ toJson(github)}} ${{ github.event.pull_request.state }}
        run: |
          echo -e "Github context:\n$GH"
  report-comment:
    runs-on: ubuntu-latest
    needs:
      - deploy-job
    if: needs.deploy-job.result != 'skipped'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 CI result: ${{ needs.deploy-job.result }}.'
            })
