name: Deploy
run-name: Deploy conditions test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - edited
env:
  SOME_VAR: some value
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.state == 'open' && (
        contains(github.event.pull_request.labels.*.name, 'deploy') ||
        endsWith(github.event.pull_request.title, '[deploy]')
      ) && (
        contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action) ||
        github.event.action == 'labeled' && github.event.label.name == 'deploy' ||
        github.event.action == 'edited' && endsWith(github.event.pull_request.title, '[deploy]')
      )
    steps:
      - run: echo "Start"
      - name: GH context
        env:
          GH: ${{ toJson(github)}} ${{ github.event.pull_request.state }}
        run: |
          echo -e "Github context:\n$GH"
      # - name: Fail step
      #   id: fail-step
      #   run: |
      #     asdfasdfasdf
      - uses: actions/github-script@v7
        name: comment after failure
        if: always()
        with:
          script: |
            const status = "${{ job.status }}";
            let body = `Deployment result: ${status}`;
            if (status == "success") {
              body += "\nSome variable: ${{ github.event.pull_request.url }}--${{ env.SOME_VAR }}\nAlso here is empty var value: ${{ env.EMPTY_VAR }}"
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
  js-job:
    name: Test JS Job
    runs-on: ubuntu-latest
    needs: deploy-job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -x
          pwd
          ls -hal /home/runner/work/test/test/.github/actions/js-action
          ls -hal ./
      - name: Test JS Job
        id: js-job
        uses: ./.github/actions/js-action
        with:
          name: tester
          payload: '{ "key": "value", "key2": "value2" }'
  report-job:
    needs: deploy-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install netlify
      - uses: actions/github-script@v7
        name: set check
        with:
          script: |
            const netlify = require('netlify');
            var run = true;
            var count = 60;
            async function countdown() {
              console.log(`Countdown tick: ${count}`);
              await new Promise((f) => setTimeout(f, 1000));
              count--;
              if (count <= 0) {
                run = false;
              }
              console.log(`Countdown done: ${count}`);
            }
            async function test() {
              console.log("Start countdown");
              while (run) {
                await countdown();
              }
              console.log("Stop countdown");
            }
            console.log("START");
            await test();
            console.log("DONE");
